<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RunSettingsFilePath>D:\.NET 10 SD\ECommerceBackend\ECommerce.IntegrationTests\bin\Debug\net10.0\fine-code-coverage\coverage-tool-output\ECommerce.IntegrationTests-fcc-mscodecoverage-generated.runsettings</RunSettingsFilePath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite.Core" />
    <PackageReference Include="Moq" />    
    <PackageReference Include="Testcontainers" />
    <PackageReference Include="Testcontainers.MsSql" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="FluentAssertions" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\ECommerce.Api\ECommerce.Api.csproj" />
    <ProjectReference Include="..\ECommerce.Application\ECommerce.Application.csproj" /> 
    <ProjectReference Include="..\ECommerce.Domain\ECommerce.Domain.csproj" />
    <ProjectReference Include="..\ECommerce.Infrastructure\ECommerce.Infrastructure.csproj" />
  </ItemGroup>

</Project>
