# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - dev-app-ecommerce-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    env:
      KeyVault__DevelopmentVaultUri: ${{ secrets.KEYVAULT_DEVELOPMENTVAULTURI }}
      Jwt__Secret: ${{ secrets.JWT_SECRET }}
      Jwt__RefreshTokenExpiryDays: ${{ secrets.JWT_REFRESHTOKENEXPIRYDAYS }}
      Jwt__Issuer: ${{ secrets.JWT_ISSUER }}
      Jwt__Audience: ${{ secrets.JWT_AUDIENCE }}
      Jwt__ExpiryMinutes: ${{ secrets.JWT_EXPIRYMINUTES }}
      Jwt__KeyId: ${{ secrets.JWT_KEYID }}
      Hash__Secret: ${{ secrets.HASH_SECRET }}
      Encryption__OneTimePasswordKey: ${{ secrets.ENCRYPTION_ONETIMEPASSWORDKEY }}
      ConnectionStrings__DefaultConnection: ${{ secrets.CONNECTIONSTRINGS_DEFAULTCONNECTION }}

    steps:
      - uses: actions/checkout@v5

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.x'

      - name: Restore NuGet packages
        run: dotnet restore ECommerce.Api/ECommerce.Api.csproj
        
      - name: Build main project
        run: dotnet build ECommerce.Api/ECommerce.Api.csproj -c Release

      - name: Sync clock
        run: sudo chronyc makestep || sudo ntpdate pool.ntp.org || true

      - name: Run Tests
        run: |
          dotnet test ./ECommerce.ArchitectureTests/ECommerce.ArchitectureTests.csproj -c Release --logger "console;verbosity=detailed"
          dotnet test ./ECommerce.UnitTests/ECommerce.UnitTests.csproj -c Release --logger "console;verbosity=detailed"
          dotnet test ./ECommerce.IntegrationTests/ECommerce.IntegrationTests.csproj -c Release --logger "console;verbosity=detailed"
        
      - name: Clean publish folder
        run: rm -rf ${{env.DOTNET_ROOT}}/myapp
        
      - name: Publish main project only
        run: dotnet publish ECommerce.Api/ECommerce.Api.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp --no-dependencies
 
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4.6.2
        with:
            name: .net-app
            path: ${{env.DOTNET_ROOT}}/myapp 
            
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4.3.0
        with:
          name: .net-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dev-app-ecommerce-api'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E8BDE2EE994C46E892CC64FB2D5C702F }}
